"use client";
import{Palette,Upload,Save,CheckCircle2}from"lucide-react";import{useEffect,useState}from"react";import{createClient}from"@/lib/supabase/client";import{CURRENCIES}from"@/lib/constants";import{Topbar}from"@/components/Topbar";import{useTheme}from"@/components/ThemeProvider";import type{Business,ThemeName}from"@/lib/types";
export default function SettingsPage(){const[data,setData]=useState<Business|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[done,setDone]=useState(false);const{mode,setMode}=useTheme();
 useEffect(()=>{(async()=>{const sb=createClient();const{data:{user}}=await sb.auth.getUser();if(!user)return;const{data:b}=await sb.from("bizdocs_businesses").select("*").eq("owner_id",user.id).single();setData(b);setLoading(false)})()},[]);
 const set=(key:string,value:any)=>setData(d=>d?({...d,[key]:value}):d);
 async function save(){if(!data)return;setSaving(true);setDone(false);const sb=createClient();const{error}=await sb.from("bizdocs_businesses").update({name:data.name,business_type:data.business_type,phone:data.phone,email:data.email,website:data.website,address:data.address,brand_color:data.brand_color,accent_color:data.accent_color,theme:data.theme,default_currency:data.default_currency,default_tax_rate:Number(data.default_tax_rate)||0,tax_enabled:data.tax_enabled,payment_terms:data.payment_terms,default_footer:data.default_footer,payment_info:data.payment_info,prefixes:data.prefixes}).eq("id",data.id);setSaving(false);if(!error)setDone(true)}
 async function upload(file:File){if(!data||!file)return;const sb=createClient();const{data:{user}}=await sb.auth.getUser();if(!user)return;const ext=file.name.split(".").pop()||"png";const path=user.id+"/logo."+ext;const up=await sb.storage.from("bizdocs-assets").upload(path,file,{upsert:true,contentType:file.type});if(up.error)return;const url=sb.storage.from("bizdocs-assets").getPublicUrl(path).data.publicUrl;setData({...data,logo_url:url});await sb.from("bizdocs_businesses").update({logo_url:url}).eq("id",data.id)}
 if(loading)return <div><Topbar title="Settings"/><div className="mx-auto max-w-[850px] px-4 py-10"><div className="h-28 animate-pulse rounded-2xl bg-[var(--surface-2)]"/></div></div>;
 if(!data)return <div><Topbar title="Settings"/><div className="p-8">Workspace not found.</div></div>;
 return <div className="page-enter"><Topbar title="Settings" action={done?<span className="inline-flex items-center gap-1.5 text-xs font-semibold text-[var(--success)]"><CheckCircle2 size={15}/>Saved</span>:null}/><div className="mx-auto max-w-[850px] px-4 py-7 sm:px-6 lg:px-8"><div className="space-y-5">
 <section className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="font-semibold text-[var(--text-strong)]">Business profile</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><label className="label">Business name</label><input className="field" value={data.name} onChange={e=>set("name",e.target.value)}/></div><div><label className="label">Business type</label><input className="field" value={data.business_type||""} onChange={e=>set("business_type",e.target.value)}/></div><div><label className="label">Email</label><input className="field" type="email" value={data.email||""} onChange={e=>set("email",e.target.value)}/></div><div><label className="label">Phone</label><input className="field" value={data.phone||""} onChange={e=>set("phone",e.target.value)}/></div><div><label className="label">Website</label><input className="field" value={data.website||""} onChange={e=>set("website",e.target.value)}/></div><div><label className="label">Address</label><input className="field" value={data.address||""} onChange={e=>set("address",e.target.value)}/></div></div></section>
 <section className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5"><div className="flex items-center gap-2"><Palette size={17} className="text-[var(--brand)]"/><h2 className="font-semibold text-[var(--text-strong)]">Branding</h2></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><label className="label">Logo</label><div className="flex items-center gap-3"><div className="grid h-14 w-14 place-items-center overflow-hidden rounded-xl border border-[var(--line)] bg-[var(--surface-2)]">{data.logo_url?<img src={data.logo_url} alt="" className="h-full w-full object-contain"/>:<span className="text-xs font-bold text-[var(--brand)]">{data.name.slice(0,2).toUpperCase()}</span>}</div><label className="btn-secondary cursor-pointer"><Upload size={15}/>Upload<input type="file" className="hidden" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/></label></div></div><div><label className="label">Primary brand color</label><div className="flex gap-2"><input type="color" className="h-10 w-12 rounded-lg border border-[var(--line)] bg-[var(--surface)]" value={data.brand_color} onChange={e=>set("brand_color",e.target.value)}/><input className="field" value={data.brand_color} onChange={e=>set("brand_color",e.target.value)}/></div></div><div><label className="label">Accent color</label><div className="flex gap-2"><input type="color" className="h-10 w-12 rounded-lg border border-[var(--line)] bg-[var(--surface)]" value={data.accent_color} onChange={e=>set("accent_color",e.target.value)}/><input className="field" value={data.accent_color} onChange={e=>set("accent_color",e.target.value)}/></div></div><div><label className="label">Document theme</label><select className="field" value={data.theme} onChange={e=>set("theme",e.target.value as ThemeName)}>{["classic","modern","executive","minimal"].map(x=><option key={x}>{x}</option>)}</select></div></div></section>
 <section className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="font-semibold text-[var(--text-strong)]">Documents & currency</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><label className="label">Currency</label><select className="field" value={data.default_currency} onChange={e=>set("default_currency",e.target.value)}>{CURRENCIES.map(c=><option key={c.code}>{c.code}</option>)}</select></div><div><label className="label">Default tax rate (%)</label><input className="field" type="number" min="0" max="100" value={data.default_tax_rate} onChange={e=>set("default_tax_rate",Number(e.target.value))}/></div><label className="flex items-center gap-3 rounded-xl border border-[var(--line)] p-3 text-sm font-semibold"><input type="checkbox" checked={data.tax_enabled} onChange={e=>set("tax_enabled",e.target.checked)}/> Enable tax by default</label><div><label className="label">Default payment terms</label><input className="field" value={data.payment_terms||""} onChange={e=>set("payment_terms",e.target.value)}/></div><div className="sm:col-span-2"><label className="label">Default footer</label><input className="field" value={data.default_footer||""} onChange={e=>set("default_footer",e.target.value)} placeholder="Business name · website · phone"/></div></div></section>
 <section className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="font-semibold text-[var(--text-strong)]">Payment information</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{["bank","accountName","accountNumber","branch","mobileMoney","paymentPhone"].map(k=><div key={k}><label className="label">{k.replace(/([A-Z])/g," $1")}</label><input className="field" value={data.payment_info?.[k]||""} onChange={e=>set("payment_info",{...(data.payment_info||{}),[k]:e.target.value})}/></div>)}</div></section>
 <section className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="font-semibold text-[var(--text-strong)]">Appearance</h2><div className="mt-4 grid grid-cols-3 gap-2">{["light","dark","system"].map(x=><button key={x} onClick={()=>setMode(x as any)} className={`rounded-xl border px-3 py-3 text-sm font-semibold capitalize ${mode===x?"border-[var(--brand)] bg-[var(--accent)] text-[var(--brand)]":"border-[var(--line)] text-[var(--text-muted)]"}`}>{x}</button>)}</div></section>
 <div className="flex justify-end"><button onClick={save} disabled={saving} className="btn-primary px-5"><Save size={15}/>{saving?"Saving...":"Save changes"}</button></div>
 </div></div></div>}
