"use client";
import {Edit2,Plus,Search,Trash2,X} from "lucide-react";import{useMemo,useState}from"react";import{createClient}from"@/lib/supabase/client";import type{Client}from"@/lib/types";
const empty={name:"",company:"",email:"",phone:"",address:"",notes:""};
export function ClientsManager({businessId,initial}:{businessId:string;initial:Client[]}){const[items,setItems]=useState(initial),[q,setQ]=useState(""),[form,setForm]=useState<any|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const shown=useMemo(()=>items.filter(c=>[c.name,c.company,c.email,c.phone].some(v=>String(v||"").toLowerCase().includes(q.toLowerCase()))),[items,q]);
 async function save(){if(!form?.name?.trim())return;setSaving(true);setError("");const sb=createClient();const payload={business_id:businessId,name:form.name.trim(),company:form.company||null,email:form.email||null,phone:form.phone||null,address:form.address||null,notes:form.notes||null};const r=form.id?await sb.from("bizdocs_clients").update(payload).eq("id",form.id).select("*").single():await sb.from("bizdocs_clients").insert(payload).select("*").single();setSaving(false);if(r.error){setError("We couldn't save this client. Please try again.");return}setItems(x=>form.id?x.map(c=>c.id===form.id?r.data:c):[r.data,...x]);setForm(null)}
 async function remove(id:string){if(!confirm("Delete this client?"))return;const r=await createClient().from("bizdocs_clients").delete().eq("id",id);if(!r.error)setItems(x=>x.filter(c=>c.id!==id))}
 return <div><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-3 text-[var(--text-soft)]"/><input className="field pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search clients"/></div><button onClick={()=>setForm(empty)} className="btn-primary"><Plus size={16}/>Add client</button></div><div className="mt-5 overflow-hidden rounded-2xl border border-[var(--line)] bg-[var(--surface)]">{shown.length===0?<div className="px-5 py-14 text-center"><p className="font-semibold text-[var(--text-strong)]">No clients yet</p><p className="mt-1 text-sm text-[var(--text-muted)]">Add a client to make document creation faster.</p><button onClick={()=>setForm(empty)} className="btn-primary mt-5">Add Client</button></div>:<div className="divide-y divide-[var(--line)]">{shown.map(c=><div key={c.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="min-w-0"><div className="truncate text-sm font-semibold text-[var(--text-strong)]">{c.company||c.name}</div><div className="truncate text-xs text-[var(--text-soft)]">{c.company&&c.name+" · "}{c.email||c.phone||"No contact details"}</div></div><div className="flex gap-1"><button onClick={()=>setForm(c)} className="rounded-lg p-2 text-[var(--text-muted)] hover:bg-[var(--surface-2)]" aria-label="Edit"><Edit2 size={15}/></button><button onClick={()=>remove(c.id)} className="rounded-lg p-2 text-[var(--text-soft)] hover:bg-red-50 hover:text-[var(--danger)]" aria-label="Delete"><Trash2 size={15}/></button></div></div>)}</div>}</div>
 {form&&<div className="fixed inset-0 z-[90] grid place-items-center bg-black/35 p-4"><div className="w-full max-w-[560px] rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="font-semibold text-[var(--text-strong)]">{form.id?"Edit client":"Add client"}</h2><button onClick={()=>setForm(null)}><X size={18}/></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><input className="field" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Contact name *"/><input className="field" value={form.company} onChange={e=>setForm({...form,company:e.target.value})} placeholder="Company"/><input className="field" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email"/><input className="field" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Phone"/><input className="field sm:col-span-2" value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Address"/><textarea className="field sm:col-span-2 min-h-24" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Notes"/></div>{error&&<p className="mt-3 text-xs text-[var(--danger)]">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button onClick={()=>setForm(null)} className="btn-secondary">Cancel</button><button disabled={saving} onClick={save} className="btn-primary">{saving?"Saving...":"Save client"}</button></div></div></div>}
 </div>}
