"use client";

import {ChevronDown,ChevronUp,Download,GripVertical,Loader2,Plus,Printer,Save,Send,Share2,Sparkles,Trash2,X} from "lucide-react";
import {useEffect,useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import {calculateItem,calculateTotals} from "@/lib/calculations";
import {DOCUMENT_TYPES,documentLabel,formatMoney,PREFIXES,CURRENCIES} from "@/lib/constants";
import type {Business,Client,DocumentData,DocumentStatus,DocumentType,LineItem,Product,ThemeName} from "@/lib/types";
import {DocumentRenderer} from "@/components/DocumentRenderer";import {StatementEditor} from "@/components/StatementEditor";

function today(){return new Date().toISOString().slice(0,10)}
function blankItem():LineItem{return{description:"",quantity:1,unit:"item",unitPrice:0,discount:0,taxRate:0,amount:0}}
function initialData(b:Business,type:DocumentType):DocumentData{const tax=b.tax_enabled?Number(b.default_tax_rate):0;return{type,number:"",status:"draft",issueDate:today(),dueDate:type==="invoice"?new Date(Date.now()+14*86400000).toISOString().slice(0,10):"",validUntil:type==="quotation"?new Date(Date.now()+7*86400000).toISOString().slice(0,10):"",currency:b.default_currency,client:{},items:[{...blankItem(),taxRate:tax}],subtotal:0,discount:0,tax:0,total:0,notes:"",terms:b.payment_terms||"",paymentMethod:"",paymentReference:"",paymentInfo:b.payment_info||{},receivedFrom:"",amountPaid:0,deliveryAddress:"",receivedBy:"",signatureName:"",payload:{},theme:b.theme||"modern",branding:{businessName:b.name,logoUrl:b.logo_url,brandColor:b.brand_color,accentColor:b.accent_color,footer:b.default_footer,phone:b.phone,email:b.email,address:b.address,website:b.website}}}
function fromRow(row:any,b:Business,clients:Client[]):DocumentData{const p=row.payload||{};return{...initialData(b,row.type),id:row.id,type:row.type,number:row.number,status:row.status,issueDate:row.issue_date,dueDate:row.due_date||"",validUntil:row.valid_until||"",currency:row.currency,subtotal:Number(row.subtotal),discount:Number(row.discount),tax:Number(row.tax),total:Number(row.total),notes:row.notes||"",terms:row.terms||"",theme:row.theme,branding:{...initialData(b,row.type).branding,...(row.branding||{})},client:clients.find(c=>c.id===row.client_id)||{},items:(row.items||[]).map((i:any)=>({id:i.id,description:i.description,quantity:Number(i.quantity),unit:i.unit,unitPrice:Number(i.unit_price),discount:Number(i.discount),taxRate:Number(i.tax_rate||0),amount:Number(i.amount)})),paymentInfo:p.paymentInfo||b.payment_info||{},paymentMethod:p.paymentMethod||"",paymentReference:p.paymentReference||"",receivedFrom:p.receivedFrom||"",amountPaid:Number(p.amountPaid||0),deliveryAddress:p.deliveryAddress||"",receivedBy:p.receivedBy||"",signatureName:p.signatureName||"",payload:p}}
function getPrefix(b:Business,t:DocumentType){return b.prefixes?.[t]||PREFIXES[t]}
function recalc(d:DocumentData){const items=d.items.map(i=>({...i,amount:calculateItem(i).amount}));const totals=calculateTotals(items);return{...d,items,subtotal:totals.subtotal,discount:totals.discount,tax:totals.tax,total:totals.total}}

export function DocumentStudio({business,clients,products,initial,initialType}:{business:Business;clients:Client[];products:Product[];initial?:DocumentData|null;initialType?:DocumentType}){
 const router=useRouter();const previewRef=useRef<HTMLDivElement>(null);const[active,setActive]=useState<"editor"|"preview">("editor");const[saving,setSaving]=useState(false);const[saved,setSaved]=useState(false);const[error,setError]=useState("");const[aiOpen,setAiOpen]=useState(false);const[aiMode,setAiMode]=useState<"generate"|"rewrite">("generate");const[aiText,setAiText]=useState("");const[aiBusy,setAiBusy]=useState(false);const[statusOpen,setStatusOpen]=useState(false);
 const[type,setType]=useState<DocumentType>(initial?.type||initialType||"invoice");const[data,setData]=useState<DocumentData>(()=>recalc(initial||initialData(business,initialType||"invoice")));const[draftReady,setDraftReady]=useState(false);
 useEffect(()=>{const key=`bizdocs-draft-${data.id||"new"}`;localStorage.setItem(key,JSON.stringify(data));setDraftReady(true)},[data]);
 useEffect(()=>{if(!initial&&!data.id){const raw=localStorage.getItem("bizdocs-draft-new");if(raw){try{const x=JSON.parse(raw);if(x?.businessName!==false)setData(recalc(x))}catch{}}}},[]);
 const set=(patch:Partial<DocumentData>)=>setData(d=>recalc({...d,...patch}));
 const setPayload=(patch:Record<string,unknown>)=>setData(d=>recalc({...d,payload:{...d.payload,...patch}}));
 const updateItem=(index:number,patch:Partial<LineItem>)=>setData(d=>recalc({...d,items:d.items.map((it,i)=>i===index?{...it,...patch}:it)}));
 function chooseType(next:DocumentType){setType(next);setData(d=>recalc({...d,type:next,number:"",validUntil:next==="quotation"?d.validUntil:"",dueDate:next==="invoice"?d.dueDate:""}));}
 async function save(manual=false){setSaving(true);setSaved(false);setError("");try{const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Your session has expired. Please sign in again.");let doc=data;
   if(!doc.id){const{data:numberData,error:numberError}=await supabase.rpc("bizdocs_next_number",{p_business_id:business.id,p_document_type:doc.type,p_prefix:getPrefix(business,doc.type)});if(numberError)throw numberError;doc={...doc,number:String(numberData)}}
   const payload={...doc.payload,paymentInfo:doc.paymentInfo,paymentMethod:doc.paymentMethod,paymentReference:doc.paymentReference,receivedFrom:doc.receivedFrom,amountPaid:doc.amountPaid,deliveryAddress:doc.deliveryAddress,receivedBy:doc.receivedBy,signatureName:doc.signatureName};
   const row={business_id:business.id,user_id:user.id,type:doc.type,number:doc.number,status:doc.status,client_id:doc.client.id||null,issue_date:doc.issueDate||today(),due_date:doc.dueDate||null,valid_until:doc.validUntil||null,currency:doc.currency,subtotal:doc.subtotal,discount:doc.discount,tax:doc.tax,total:doc.total,notes:doc.notes,terms:doc.terms,theme:doc.theme,branding:doc.branding,payload};
   const result=doc.id?await supabase.from("bizdocs_documents").update(row).eq("id",doc.id).select("id").single():await supabase.from("bizdocs_documents").insert(row).select("id").single();
   if(result.error)throw result.error;const id=result.data!.id;
   await supabase.from("bizdocs_document_items").delete().eq("document_id",id);
   if(doc.items.length) {const ins=await supabase.from("bizdocs_document_items").insert(doc.items.map((i,n)=>({document_id:id,description:i.description||"Item",quantity:i.quantity,unit:i.unit,unit_price:i.unitPrice,discount:i.discount,tax:i.taxRate,amount:i.amount,position:n})));if(ins.error)throw ins.error}
   if(isNew||manual)await supabase.from("bizdocs_activity_logs").insert({business_id:business.id,user_id:user.id,action:isNew?"document_created":"document_updated",entity_type:"document",entity_id:id,metadata:{type:doc.type,number:doc.number}});
   const savedDoc={...doc,id};lastSaved.current=JSON.stringify(savedDoc);setData(savedDoc);localStorage.removeItem("bizdocs-draft-new");setSaved(true);if(isNew)router.replace(`/app/documents/${id}`);return savedDoc;
 }catch(e:any){if(!navigator.onLine){setError("You're offline. Your changes are saved locally and will stay available until you reconnect.");}else setError(e?.message||"We couldn't save your document. Please try again.");}finally{setSaving(false)}}
 const lastSaved=useRef("");useEffect(()=>{if(!draftReady||!data.id)return;const snapshot=JSON.stringify(data);const h=setTimeout(()=>{if(snapshot!==lastSaved.current)save(false)},1400);return()=>clearTimeout(h)},[data,draftReady]);
 async function pdf(){if(!previewRef.current)return;setError("");try{setSaving(true);const{default:html2canvas}=await import("html2canvas");const{default:jsPDF}=await import("jspdf");const pages=Array.from(previewRef.current.querySelectorAll<HTMLElement>(".pdf-page"));const docPdf=new jsPDF({unit:"mm",format:"a4",orientation:"portrait"});for(let i=0;i<pages.length;i++){const canvas=await html2canvas(pages[i],{scale:2,useCORS:true,backgroundColor:"#ffffff"});const img=canvas.toDataURL("image/jpeg",.94);if(i)docPdf.addPage();docPdf.addImage(img,"JPEG",0,0,210,297)}docPdf.save(`${data.number||"bizdocs-document"}.pdf`);const supabase=createClient();if(data.id){const{data:{user}}=await supabase.auth.getUser();if(user)await supabase.from("bizdocs_activity_logs").insert({business_id:business.id,user_id:user.id,action:"document_downloaded",entity_type:"document",entity_id:data.id})}}catch{setError("We couldn't generate the PDF. Please try again.")}finally{setSaving(false)}}
 async function share(){const message=`Hello ${data.client.name||"there"},\nPlease find ${documentLabel(data.type)} ${data.number||""} from ${business.name}.\nTotal: ${formatMoney(data.total,data.currency)}\nThank you for your business.`;try{if("share"in navigator){await(navigator as any).share({title:`${documentLabel(data.type)} ${data.number}`,text:message})}else{window.open(`https://wa.me/?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer")}}catch{}}
 async function ai(){if(!aiText.trim())return;setAiBusy(true);setError("");try{const r=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:aiMode,input:aiText,type:data.type,currency:data.currency,current:data})});const j=await r.json();if(!r.ok)throw new Error(j.error||"AI generation failed");if(aiMode==="generate"){const x=j.data;setData(d=>recalc({...d,type:x.documentType||d.type,client:{...d.client,name:x.client?.name||d.client.name,company:x.client?.company||d.client.company,email:x.client?.email||d.client.email,phone:x.client?.phone||d.client.phone,address:x.client?.address||d.client.address},items:(x.items||[]).map((i:any)=>({description:i.description||"",quantity:Number(i.quantity||1),unit:i.unit||"item",unitPrice:Number(i.unitPrice||0),discount:Number(i.discount||0),taxRate:Number(i.taxRate||0),amount:0})),payload:{...d.payload,project:x.project||d.payload.project,timeline:x.timeline||d.payload.timeline},notes:x.notes||d.notes,terms:x.terms||d.terms}));}else{if(j.data?.text)set((aiText.includes(data.notes)?{notes:j.data.text}:{notes:j.data.text}))}setAiOpen(false);setAiText("")}catch(e:any){setError(e?.message||"AI couldn't complete that request.")}finally{setAiBusy(false)}}
 const editor=<div className="space-y-4">
   <section className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-4"><label className="label">Document type</label><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{DOCUMENT_TYPES.map(t=><button key={t.type} onClick={()=>chooseType(t.type)} className={`rounded-xl border px-3 py-2.5 text-left text-xs font-semibold ${data.type===t.type?"border-[var(--brand)] bg-[var(--accent)] text-[var(--brand)]":"border-[var(--line)] text-[var(--text-muted)] hover:bg-[var(--surface-2)]"}`}>{t.label}<span className="mt-0.5 block text-[10px] font-normal opacity-75">{t.description}</span></button>)}</div></section>
   <section className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-4"><div className="grid gap-4 sm:grid-cols-3"><div><label className="label">Document number</label><input className="field" value={data.number} onChange={e=>set({number:e.target.value})} placeholder="Auto generated"/></div><div><label className="label">Issue date</label><input type="date" className="field" value={data.issueDate} onChange={e=>set({issueDate:e.target.value})}/></div><div><label className="label">{data.type==="quotation"?"Valid until":"Due date"}</label><input type="date" className="field" value={(data.type==="quotation"?data.validUntil:data.dueDate)||""} onChange={e=>set(data.type==="quotation"?{validUntil:e.target.value}:{dueDate:e.target.value})}/></div></div></section>
   <section className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-4"><h2 className="text-sm font-semibold text-[var(--text-strong)]">Client</h2><div className="mt-3"><input className="field" list="bizdocs-clients" value={data.client.company||data.client.name||""} onChange={e=>{const v=e.target.value;const c=clients.find(x=>x.company===v||x.name===v);set({client:c?c:{name:v}})}} placeholder="Search or type a client"/><datalist id="bizdocs-clients">{clients.map(c=><option key={c.id} value={c.company||c.name}/>)}</datalist></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><input className="field" value={data.client.name||""} onChange={e=>set({client:{...data.client,name:e.target.value}})} placeholder="Contact name"/><input className="field" value={data.client.email||""} onChange={e=>set({client:{...data.client,email:e.target.value}})} placeholder="Email"/><input className="field" value={data.client.phone||""} onChange={e=>set({client:{...data.client,phone:e.target.value}})} placeholder="Phone"/><input className="field" value={data.client.address||""} onChange={e=>set({client:{...data.client,address:e.target.value}})} placeholder="Address"/></div></section>
   {data.type==="statement"?<StatementEditor transactions={(data.payload.transactions||[]) as any[]} openingBalance={Number(data.payload.openingBalance||0)} currency={data.currency} onOpeningChange={v=>setPayload({openingBalance:Number(v)||0})} onChange={tx=>setPayload({transactions:tx})}/>:<section className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-4"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-[var(--text-strong)]">Items</h2><button onClick={()=>setData(d=>recalc({...d,items:[...d.items,blankItem()]}))} className="btn-secondary py-2 text-xs"><Plus size={15}/>Add item</button></div><div className="mt-4 space-y-3">{data.items.map((it,i)=><div key={i} className="rounded-xl border border-[var(--line)] p-3"><div className="flex items-start gap-2"><GripVertical size={16} className="mt-2.5 shrink-0 text-[var(--text-soft)]"/><div className="grid min-w-0 flex-1 gap-2 md:grid-cols-[1fr_70px_80px_120px_80px_28px]"><div className="relative"><input className="field" list={`product-${i}`} value={it.description} onChange={e=>{const value=e.target.value;const product=products.find(p=>p.name===value);updateItem(i,product?{description:product.description||product.name,unit:product.unit,unitPrice:Number(product.default_price),taxRate:Number(product.tax_rate)}:{description:value})}} placeholder="Service or product"/><datalist id={`product-${i}`}>{products.map(p=><option key={p.id} value={p.name}/>)}</datalist></div><input className="field" type="number" min=".001" step=".001" value={it.quantity} onChange={e=>updateItem(i,{quantity:Number(e.target.value)})}/><input className="field" value={it.unit} onChange={e=>updateItem(i,{unit:e.target.value})}/><input className="field text-right" type="number" min="0" value={it.unitPrice} onChange={e=>updateItem(i,{unitPrice:Number(e.target.value)})}/><input className="field text-right" type="number" min="0" max="100" value={it.taxRate} onChange={e=>updateItem(i,{taxRate:Number(e.target.value)})}/><button onClick={()=>setData(d=>recalc({...d,items:d.items.filter((_,n)=>n!==i)}))} className="grid h-10 w-10 place-items-center rounded-xl text-[var(--danger)] hover:bg-red-50" aria-label="Remove item"><Trash2 size={16}/></button></div></div><div className="mt-2 flex items-center justify-between pl-6 text-xs text-[var(--text-soft)]"><span>{formatMoney(calculateItem(it).amount,data.currency)}</span><div className="flex gap-1"><button onClick={()=>i>0&&setData(d=>{const x=[...d.items];[x[i-1],x[i]]=[x[i],x[i-1]];return recalc({...d,items:x})})} className="rounded-lg p-1 hover:bg-[var(--surface-2)]"><ChevronUp size={14}/></button><button onClick={()=>i<data.items.length-1&&setData(d=>{const x=[...d.items];[x[i+1],x[i]]=[x[i],x[i+1]];return recalc({...d,items:x})})} className="rounded-lg p-1 hover:bg-[var(--surface-2)]"><ChevronDown size={14}/></button></div></div></div>)}</div></section>:null}