"use client";
import{Edit2,Plus,Search,Trash2,X}from"lucide-react";import{useMemo,useState}from"react";import{createClient}from"@/lib/supabase/client";import type{Product}from"@/lib/types";import{formatMoney}from"@/lib/constants";
const empty={name:"",description:"",unit:"item",default_price:0,tax_rate:0};
export function ProductsManager({businessId,initial,currency}:{businessId:string;initial:Product[];currency:string}){const[items,setItems]=useState(initial),[q,setQ]=useState(""),[form,setForm]=useState<any|null>(null),[saving,setSaving]=useState(false);const shown=useMemo(()=>items.filter(p=>[p.name,p.description,p.unit].some(v=>String(v||"").toLowerCase().includes(q.toLowerCase()))),[items,q]);
 async function save(){if(!form?.name?.trim())return;setSaving(true);const sb=createClient();const payload={business_id:businessId,name:form.name.trim(),description:form.description||null,unit:form.unit||"item",default_price:Number(form.default_price)||0,tax_rate:Number(form.tax_rate)||0};const r=form.id?await sb.from("bizdocs_products").update(payload).eq("id",form.id).select("*").single():await sb.from("bizdocs_products").insert(payload).select("*").single();setSaving(false);if(r.error)return;if(form.id)setItems(x=>x.map(p=>p.id===form.id?r.data:p));else setItems(x=>[r.data,...x]);setForm(null)}
 async function remove(id:string){if(!confirm("Delete this product or service?"))return;const r=await createClient().from("bizdocs_products").delete().eq("id",id);if(!r.error)setItems(x=>x.filter(p=>p.id!==id))}
 return <div><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-3 text-[var(--text-soft)]"/><input className="field pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products and services"/></div><button onClick={()=>setForm(empty)} className="btn-primary"><Plus size={16}/>Add product</button></div><div className="mt-5 overflow-hidden rounded-2xl border border-[var(--line)] bg-[var(--surface)]">{shown.length===0?<div className="px-5 py-14 text-center"><p className="font-semibold text-[var(--text-strong)]">No products or services yet</p><p className="mt-1 text-sm text-[var(--text-muted)]">Save commonly used items to speed up document creation.</p><button onClick={()=>setForm(empty)} className="btn-primary mt-5">Add item</button></div>:<div className="divide-y divide-[var(--line)]">{shown.map(p=><div key={p.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="min-w-0"><div className="truncate text-sm font-semibold text-[var(--text-strong)]">{p.name}</div><div className="truncate text-xs text-[var(--text-soft)]">{p.description||p.unit} · {formatMoney(Number(p.default_price),currency)} · Tax {p.tax_rate}%</div></div><div className="flex gap-1"><button onClick={()=>setForm(p)} className="rounded-lg p-2 text-[var(--text-muted)] hover:bg-[var(--surface-2)]"><Edit2 size={15}/></button><button onClick={()=>remove(p.id)} className="rounded-lg p-2 text-[var(--text-soft)] hover:bg-red-50 hover:text-[var(--danger)]"><Trash2 size={15}/></button></div></div>)}</div>}</div>
 {form&&<div className="fixed inset-0 z-[90] grid place-items-center bg-black/35 p-4"><div className="w-full max-w-[560px] rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="font-semibold text-[var(--text-strong)]">{form.id?"Edit item":"Add product or service"}</h2><button onClick={()=>setForm(null)}><X size={18}/></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><input className="field sm:col-span-2" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Name *"/><textarea className="field sm:col-span-2 min-h-24" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description"/><input className="field" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} placeholder="Unit"/><input className="field" type="number" min="0" value={form.default_price} onChange={e=>setForm({...form,default_price:Number(e.target.value)})} placeholder="Default price"/><input className="field" type="number" min="0" max="100" value={form.tax_rate} onChange={e=>setForm({...form,tax_rate:Number(e.target.value)})} placeholder="Tax %"/></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setForm(null)} className="btn-secondary">Cancel</button><button disabled={saving} onClick={save} className="btn-primary">{saving?"Saving...":"Save item"}</button></div></div></div>}
 </div>}
