"use client";
import {Plus,Trash2} from "lucide-react";
import type {StatementTransaction} from "@/lib/types";
export function StatementEditor({transactions,openingBalance,currency,onOpeningChange,onChange}:{transactions:StatementTransaction[];openingBalance:number;currency:string;onOpeningChange:(value:number)=>void;onChange:(value:StatementTransaction[])=>void}){
 function update(i:number,p:Partial<StatementTransaction>){onChange(transactions.map((x,n)=>n===i?{...x,...p}:x))}
 function add(){const prev=transactions.at(-1);const balance=prev?.balance??openingBalance;onChange([...transactions,{transactionDate:new Date().toISOString().slice(0,10),reference:"",description:"",debit:0,credit:0,balance}])}
 function recalc(list:StatementTransaction[]){let b=Number(openingBalance)||0;return list.map(x=>{b=b-Number(x.debit||0)+Number(x.credit||0);return{...x,balance:b}})}
 return <section className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-4"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold text-[var(--text-strong)]">Statement transactions</h2><p className="mt-1 text-[11px] text-[var(--text-soft)]">Debits reduce the balance; credits increase it.</p></div><button onClick={add} className="btn-secondary py-2 text-xs"><Plus size={14}/>Add transaction</button></div><div className="mt-4"><label className="label">Opening balance</label><input className="field" type="number" value={openingBalance} onChange={e=>onOpeningChange(Number(e.target.value)||0)}/></div><div className="mt-4 space-y-3">{transactions.map((t,i)=><div key={i} className="rounded-xl border border-[var(--line)] p-3"><div className="grid gap-2 sm:grid-cols-[130px_1fr_95px_95px_90px_35px]"><input className="field" type="date" value={t.transactionDate} onChange={e=>update(i,{transactionDate:e.target.value})}/><input className="field" value={t.description} onChange={e=>update(i,{description:e.target.value})} placeholder="Description"/><input className="field" type="number" min="0" value={t.debit} onChange={e=>update(i,{debit:Number(e.target.value)||0})} placeholder="Debit"/><input className="field" type="number" min="0" value={t.credit} onChange={e=>update(i,{credit:Number(e.target.value)||0})} placeholder="Credit"/><input className="field bg-[var(--surface-2)]" readOnly value={t.balance.toLocaleString()}/><button onClick={()=>onChange(transactions.filter((_,n)=>n!==i))} className="grid h-10 w-10 place-items-center rounded-xl text-[var(--danger)] hover:bg-red-50"><Trash2 size={15}/></button></div></div>)}</div><button onClick={()=>onChange(recalc(transactions))} className="mt-3 text-xs font-semibold text-[var(--brand)]">Recalculate running balances</button></section>
}
